# Build and export the non-curriculum pages as static files.

# Required substitutions
# * Probably the google secret manager info.
# * the Firebase _TARGET for the hosting, also implies existence of .firebaserc and firebase.json files.

# Global options.
options:
  machineType: "E2_HIGHCPU_32"
  env:
    - "GCP_COMMIT_SHA=$COMMIT_SHA"
    - "GCP_TAG_NAME=$TAG_NAME"

steps:
  - id: "remove-curriculum-pages"
    name: "node:18"
    entrypoint: "npm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        rm -rf ./src/pages/beta

  - id: "npm-ci"
    name: "node:18"
    entrypoint: "npm"
    args: ["ci"]

  - id: "next-build"
    name: "node:18"
    entrypoint: "npm"
    args: ["run", "build"]
    env:
      - "GOOGLE_SECRET_MANAGER_SERVICE_ACCOUNT=$_GOOGLE_SECRET_MANAGER_SERVICE_ACCOUNT"
      - "OAK_CONFIG_LOCATION=$_OAK_CONFIG_LOCATION"
      - "OVERRIDE_RELEASE_STAGE=$_OVERRIDE_RELEASE_STAGE"
      - "CLOUDBUILD_TRIGGER_NAME=$TRIGGER_NAME"
      - "CLOUDBUILD_DEPLOYMENT_BASE_URL=$_DEPLOYMENT_BASE_URL"

  - id: "next-export"
    name: "node:18"
    entrypoint: "npm"
    args: ["run", "export"]
    env:
      - "GOOGLE_SECRET_MANAGER_SERVICE_ACCOUNT=$_GOOGLE_SECRET_MANAGER_SERVICE_ACCOUNT"
      - "OAK_CONFIG_LOCATION=$_OAK_CONFIG_LOCATION"
      - "OVERRIDE_RELEASE_STAGE=$_OVERRIDE_RELEASE_STAGE"
      - "CLOUDBUILD_TRIGGER_NAME=$TRIGGER_NAME"
      - "CLOUDBUILD_DEPLOYMENT_BASE_URL=$_DEPLOYMENT_BASE_URL"

  - id: "deploy-to-firebase"
    name: gcr.io/$PROJECT_ID/firebase
    entrypoint: /bin/bash
    args:
      - "-c"
      # real deploy
      - >-
        /usr/bin/firebase.bash
        deploy
        --project=$PROJECT_ID
        --only=hosting:${_FIREBASE_TARGET}
        | tee /workspace/deploy.log

  # Possible Slack notification.
