query specialistLessonMedia(
  $programmeSlug: String
  $unitSlug: String
  $lessonSlug: String
) {
  specialistLessonMedia: published_mv_specialist_1_0_3(
    where: {
      unit_slug: { _eq: $unitSlug }
      synthetic_programme_slug: { _eq: $programmeSlug }
      lesson_slug: { _eq: $lessonSlug }
    }
  ) {
    lesson_title
    combined_programme_fields
    unit_title
    expired
    contains_copyright_content
  }
  restrictions: published_mv_lesson_content_published_2_1_0(
    where: { lesson_slug: { _eq: $lessonSlug } }
  ) {
    geo_restricted
    login_required
  }
}
