name: Custom check setting

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: set up Node
        uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true

      - run: pnpm install --frozen-lockfile --verbose
        env:
          NEXT_PUBLIC_GRAPHQL_API_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_API_URL }}

      - uses: ./.github/actions/custom_statuses
        with:
          description: fake status 1
          state: success
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/custom_statuses
        with:
          description: fake status 2
          state: failure
          github_token: ${{ secrets.GITHUB_TOKEN }}
