name: Custom check setting

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - run: npm ci
        env:
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          NEXT_PUBLIC_GRAPHQL_API_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_API_URL }}

      - uses: ./.github/actions/custom_statuses
        with:
          description: fake status 1
          state: success
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/custom_statuses
        with:
          description: fake status 2
          state: failure
          github_token: ${{ secrets.GITHUB_TOKEN }}
