name: "Set Commit Status"
description: "Creates a commit status with the provided status."
inputs:
  description:
    description: "A description of the commit state being set"
    required: true
  state:
    description: "The check conclusion, success or failure (and possibly pending later if we get clever)"
    required: true
  github_token:
    description: "A Github token, e.g. secrets.GITHUB_TOKEN"
    required: true
  target_url:
    description: "[optional] A link to further details on the status, e.g. the workflow run that caused it. Sensible default."
runs:
  using: "node20"
  main: "index.js"
