query lessonDownloadsCanonical($lessonSlug: String!) {
  mv_downloads: mv_downloads_1(where: { lesson_slug: { _eq: $lessonSlug } }) {
    downloads
    programmeSlug: programme_slug
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    lessonSlug: lesson_slug
    lessonTitle: lesson_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
    themeSlug: theme_slug
    themeTitle: theme_title
    unitSlug: unit_slug
    unitTitle: unit_title
  }
}
