query lessonListing(
  $programmeSlug: String!
  $unitSlug: String!
) {
  mv_units:mv_units_2(
    where: {
      slug: { _eq: $unitSlug }
      programme_slug: {_eq: $programmeSlug}
    }
  ) {
    programmeSlug:programme_slug
    unitSlug: slug
    unitTitle: title
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
  }
  mv_lessons: mv_lessons_3(
    order_by: { position_in_unit: asc }
    where: {
      programme_slug: {_eq: $programmeSlug}
      unit_slug: { _eq: $unitSlug }
    }
  ) {
    slug
    title
    programmeSlug: programme_slug
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
    unitSlug: unit_slug
    themeTitle: theme_title
    themeSlug: theme_slug
    description
    contentGuidance: content_guidance
    equipmentRequired: equipment_required
    supervisionLevel: supervision_level
    videoCount: video_count
    presentationCount: presentation_count
    worksheetCount: worksheet_count
    hasCopyrightMaterial: has_copyright_material
    hasDownloadableResources: has_downloadable_resources
    quizCount: quiz_count
    expired
  }
}
