query searchPage {
  mv_key_stages(order_by: { short_code: asc }) {
    shortCode: short_code
    slug
    title
  }

  mv_subjects(order_by: { title: asc }) {
    slug
    title
    keyStageSlug: key_stage_slug
  }
}
