query searchPage {
  mv_key_stages(order_by: { short_code: asc }) {
    shortCode: short_code
    slug
    title
  }

  mv_programmes_available: mv_programmes_5(order_by: { subject_title: asc }) {
    slug: subject_slug
    title: subject_title
    keyStageSlug: key_stage_slug
  }
}
