query subjectListing($keyStageSlug: String!) {
  mv_key_stages(where: { slug: { _eq: $keyStageSlug } }) {
    slug
    title
  }
  mv_programmes_available: mv_programmes_7(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      total_unit_count: { _neq: 0 }
    }
  ) {
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    programmeSlug: programme_slug
    subjectSlug: subject_slug
    subjectTitle: subject_title
    tierSlug: tier_slug
    nonDuplicateSubjectLessonCount: subject_active_lesson_count
    nonDuplicateSubjectUnitCount: subject_active_unit_count
    totalUnitCount: total_unit_count
    activeLessonCount: active_lesson_count
    activeUnitCount: active_unit_count
  }
  mv_programmes_unavailable: mv_programmes_7(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      total_unit_count: { _eq: 0 }
    }
  ) {
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    programmeSlug: programme_slug
    subjectSlug: subject_slug
    subjectTitle: subject_title
    tierSlug: tier_slug
    nonDuplicateSubjectUnitCount: subject_active_unit_count
    nonDuplicateSubjectLessonCount: subject_active_lesson_count
    totalUnitCount: total_unit_count
    activeUnitCount: active_unit_count
    activeLessonCount: active_lesson_count
  }
  keyStageList: mv_key_stages(order_by: { short_code: asc }) {
    shortCode: short_code
    slug
    title
  }
}
