query teachersKeyStageSubjectTiers(
  $keyStageSlug: String!
  $subjectSlug: String!
) {
  mv_key_stages(where: { slug: { _eq: $keyStageSlug } }) {
    slug
    title
  }
  mv_subjects: mv_subjects0000001(where: { slug: { _eq: $subjectSlug } }) {
    slug
    title
  }
  mv_tiers(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      subject_slug: { _eq: $subjectSlug }
    }
  ) {
    slug
    title
    unitCount: unit_count
    lessonCount: lesson_count
  }
}
