query teachersKeyStageSubjects($keyStageSlug: String!) {
  mv_key_stages(where: { slug: { _eq: $keyStageSlug } }) {
    slug
    title
  }
  mv_subjects: mv_subjects_2(
    order_by: { slug: asc }
    where: { key_stage_slug: { _eq: $keyStageSlug } }
  ) {
    slug
    title
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    lessonCount: lesson_count
    unitCount: unit_count
    tierCount: tier_count
    activeUnitCount: active_unit_count
  }
}
