query teachersLessonOverview(
  $lessonSlug: String!
  $keyStageSlug: String!
  $subjectSlug: String!
  $unitSlug: String!
) {
  mv_lessons: mv_lessons_3(
    where: {
      slug: { _eq: $lessonSlug }
      key_stage_slug: { _eq: $keyStageSlug }
      subject_slug: { _eq: $subjectSlug }
      unit_slug: { _eq: $unitSlug }
    }
  ) {
    slug
    title
    unitSlug: unit_slug
    unitTitle: unit_title
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
    contentGuidance: content_guidance
    equipmentRequired: equipment_required
    presentationUrl: presentation_url
    supervisionLevel: supervision_level
    worksheetUrl: worksheet_url
    hasCopyrightMaterial: has_copyright_material
    coreContent: core_content
    videoMuxPlaybackId: video_mux_playback_id
    videoWithSignLanguageMuxPlaybackId: video_with_sign_language_mux_playback_id
    transcriptSentences: transcript_sentences
    hasDownloadableResources: has_downloadable_resources
    expired
  }
  exitQuizInfo: mv_quizzes(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      subject_slug: { _eq: $subjectSlug }
      unit_slug: { _eq: $unitSlug }
      type: { _eq: "exit" }
      lesson_slug: { _eq: $lessonSlug }
    }
  ) {
    title
    questionCount: question_count
  }
  exitQuiz: mv_questions_2(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      subject_slug: { _eq: $subjectSlug }
      unit_slug: { _eq: $unitSlug }
      quiz_type: { _eq: "exit" }
      lesson_slug: { _eq: $lessonSlug }
    }
    order_by: { order: asc }
  ) {
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    lessonSlug: lesson_slug
    lessonTitle: lesson_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
    unitSlug: unit_slug
    unitTitle: unit_title
    active
    answer
    choices: choices_combined
    feedbackCorrect: feedback_correct
    feedbackIncorrect: feedback_incorrect
    images
    points
    quizType: quiz_type
    required
    title
    type
    order
    displayNumber: display_number
  }
  introQuizInfo: mv_quizzes(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      subject_slug: { _eq: $subjectSlug }
      unit_slug: { _eq: $unitSlug }
      type: { _eq: "intro" }
      lesson_slug: { _eq: $lessonSlug }
    }
  ) {
    title
    questionCount: question_count
  }
  introQuiz: mv_questions_2(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      subject_slug: { _eq: $subjectSlug }
      unit_slug: { _eq: $unitSlug }
      quiz_type: { _eq: "intro" }
      lesson_slug: { _eq: $lessonSlug }
    }
    order_by: { order: asc }
  ) {
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    lessonSlug: lesson_slug
    lessonTitle: lesson_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
    unitSlug: unit_slug
    unitTitle: unit_title
    active
    answer
    choices: choices_combined
    feedbackCorrect: feedback_correct
    feedbackIncorrect: feedback_incorrect
    images
    points
    quizType: quiz_type
    required
    title
    type
    order
    displayNumber: display_number
  }
}
