query tierListing($keyStageSlug: String!, $subjectSlug: String!) {
  mv_programmes: mv_programmes_3(
    where: {
      key_stage_slug: { _eq: $keyStageSlug }
      subject_slug: { _eq: $subjectSlug }
    }
  ) {
    programmeSlug: programme_slug
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    slug: subject_slug
    title: subject_title
    tierSlug: tier_slug
    tierTitle: tier_title
    totalUnitCount: total_unit_count
    activeLessonCount: active_lesson_count
  }
}
