query unitListing($programmeSlug: String!) {
  mv_programmes: mv_programmes_6(
    where: { programme_slug: { _eq: $programmeSlug } }
  ) {
    programmeSlug: programme_slug
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
    tierSlug: tier_slug
    totalUnitCount: active_unit_count
  }
  mv_tiers: mv_tiers_2(
    where: { current_programme_slug: { _eq: $programmeSlug } }
  ) {
    tierTitle: tier_title
    tierSlug: tier_slug
    tierProgrammeSlug: tier_programme_slug
    lessonCount: lesson_count
    unitCount: unit_count
  }
  mv_units: mv_units_3(
    where: { programme_slug: { _eq: $programmeSlug } }
    order_by: { year: asc, unit_study_order: asc }
  ) {
    slug
    title
    programmeSlug: programme_slug
    keyStageSlug: key_stage_slug
    keyStageTitle: key_stage_title
    subjectSlug: subject_slug
    subjectTitle: subject_title
    themeSlug: theme_slug
    themeTitle: theme_title
    lessonCount: lesson_count
    quizCount: quiz_count
    unitStudyOrder: unit_study_order
    year
    expired
    expiredLessonCount: expired_lesson_count
  }
}
