query GetUserListContentCount($userId: String!) {
  content_lists_aggregate(
    distinct_on: content_id
    where: { list: { user_id: { _eq: $userId } } }
  ) {
    aggregate {
      count
    }
  }
}
