query curriculumUnits($where: published_mv_curriculum_units_2_bool_exp) {
  units: published_mv_curriculum_units_2(where: $where) {
    connection_prior_unit_description
    connection_future_unit_description
    domain
    domain_id
    examboard
    examboard_slug
    keystage_slug
    lessons
    phase
    phase_slug
    planned_number_of_lessons
    slug
    subject
    subject_slug
    subject_parent
    subject_parent_slug
    threads
    tier
    tier_slug
    title
    unit_options
    year
  }
}
