query teachersSitemap {
  units: published_mv_synthetic_unitvariant_lessons_by_keystage_18_0_0(
    distinct_on: [programme_slug, unit_slug]
    where: { is_legacy: { _eq: false } }
  ) {
    unit_slug
    programme_slug
  }
  lessons: published_mv_synthetic_unitvariant_lessons_by_keystage_18_0_0(
    distinct_on: [programme_slug, unit_slug, lesson_slug]
    where: { is_legacy: { _eq: false } }
  ) {
    lesson_slug
    unit_slug
    programme_slug
  }
  programmeFilterUnits: published_mv_curriculum_sequence_b_13_0_21(
    where: {
      state: { _eq: "published" }
      lessons: { _contains: [{ _state: "published" }] }
    }
  ) {
    subject_slug
    phase_slug
    examboard_slug
    pathway_slug
    year
    keystage_slug
    subject_parent_slug
    non_curriculum
    actions
    state
  }
}
