query lessonShare(
  $lessonSlug: String!
  $unitSlug: String!
  $programmeSlug: String!
) {
  share: published_mv_lesson_content_1_3(
    where: { lesson_slug: { _eq: $lessonSlug } }
  ) {
    lesson_title
    starter_quiz
    exit_quiz
    video_mux_playback_id
    video_duration
    worksheet_asset_object_url
    expired: deprecated_fields(path: "expired")
  }
  browse: published_mv_synthetic_unitvariant_lessons_by_keystage_6_0_0(
    where: {
      lesson_slug: { _eq: $lessonSlug }
      unit_slug: { _eq: $unitSlug }
      programme_slug: { _eq: $programmeSlug }
    }
  ) {
    unit_title: unit_data(path: "title")
    is_legacy
    programme_fields
  }
}
