query lessonShare(
  $lessonSlug: String!
  $browseDataWhere: published_mv_synthetic_unitvariant_lessons_by_keystage_18_0_0_bool_exp
) {
  share: published_mv_lesson_content_published_9_0_0(
    where: { lesson_slug: { _eq: $lessonSlug } }
  ) {
    lesson_title
    starter_quiz
    exit_quiz
    video_mux_playback_id
    video_duration
    worksheet_asset_object_url
    expired: deprecated_fields(path: "expired")
    lesson_release_date
  }
  browse: published_mv_synthetic_unitvariant_lessons_by_keystage_18_0_0(
    where: $browseDataWhere
  ) {
    unit_title: unit_data(path: "title")
    lesson_slug
    unit_slug
    programme_slug
    is_legacy
    lesson_data
    unit_data
    programme_fields
    actions
    features
  }
}
