query getUserContent($userId: String, $programmeSlug: String) {
  users_content(
    where: {
      content: { programme_slug: { _eq: $programmeSlug } }
      user_id: { _eq: $userId }
    }
  ) {
    content {
      unit_slug
    }
  }
}
