version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Always increase the version requirement
    # to match the new version.
    versioning-strategy: increase

  # cloud-ops: Track updates for Terraform modules from oak-terraform-modules repository.
  - package-ecosystem: "terraform"
    directories: ["infrastructure/**/*"]
    allow:
      - dependency-name: "*::github::oaknational/oak-terraform-modules::*"
    schedule:
      interval: "daily"
