# Configuration for the GitHub Actions labeler
# This file defines rules for automatically labeling PRs based on branch names

# Label PRs from branches matching CUR-* patterns with "curric squad group"
"curric squad group":
  - head-branch: ['^[^/]+[/]CUR-.+', '^CUR-.+']  # Matches any prefix/CUR- or direct CUR- patterns 