[[plugins]]
  package = "./netlify/plugins/github-deployments"

# Cancel production builds which are not versioning commits.
[context.production]
  ignore = "node scripts/build/cancel_netlify_build.js"

  # Report production builds into Slack using custom plugin.
  [[context.production.plugins]]
    package = "./netlify/plugins/slack-reporting"

# On preview and branch deploys, use the subdomain redirect edge function
# to force all access through our managed TLD.
[[context.deploy-preview.edge_functions]]
  path = '/*'
  function = 'subdomain-redirect'
[[context.branch-deploy.edge_functions]]
  path = '/*'
  function = 'subdomain-redirect'

# Force production access to the default netlify deployment through
# our subdomain, unless it's from our load balancer.
[[context.production.edge_functions]]
  path = '/*'
  function = 'production-redirect'