[[plugins]]
package = "./netlify/plugins/github-deployments"
# Temporarily specify the Netlify next.js version to enable testing.
# Disabled while testing adding the runtime plugin from the package.json.
# [[plugins]]
# package = "@netlify/plugin-nextjs"

# Force all access through the managed TLD (default). HTTP
[[redirects]]
from = 'http://oak-web-application.netlify.app/*'
to = 'https://www.thenational.academy/:splat'
status = 302
force = true
# Force all access through the managed TLD (default). HTTPS
[[redirects]]
from = 'https://oak-web-application.netlify.app/*'
to = 'https://www.thenational.academy/:splat'
status = 302
force = true

# Force all access through the managed TLD (main branch). HTTP
[[redirects]]
from = 'http://main--oak-web-application.netlify.app/*'
to = 'https://www.thenational.academy/:splat'
status = 302
force = true
# Force all access through the managed TLD (main branch). HTTPS
[[redirects]]
from = 'https://main--oak-web-application.netlify.app/*'
to = 'https://www.thenational.academy/:splat'
status = 302
force = true

# Cancel production builds which are not versioning commits.
[context.production]
ignore = "node scripts/build/cancel_netlify_build.js"

# Report production builds into Slack using custom plugin.
[[context.production.plugins]]
package = "./netlify/plugins/slack-reporting"

# On preview and branch deploys, use the subdomain redirect edge function
# to force all access through our managed TLD.
# Note that the edge function is deployed in every context, but only
# has a path assigned in preview and branch deploys, effectively
# disabling it in production.
[[context.deploy-preview.edge_functions]]
path = '/*'
function = 'subdomain-redirect'
[[context.branch-deploy.edge_functions]]
path = '/*'
function = 'subdomain-redirect'

# Workaround for Netlify no reading .env.production.local in the new runtime yet.
# All Netlify builds are production from the Nex† perspective.
[functions]
included_files = [".env.production.local", ".next/!(cache/**)"]

[context."chore/investigate-netlify-deploy-issues-sentry-additions"]
command = "npm run build && du -sh .next/* && du -sh .netlify/functions/*"