[[plugins]]
  package = "./netlify/plugins/github-deployments"

# Cancel production builds which are not versioning commits.
[context.production]
  ignore = "node scripts/build/cancel_netlify_build.js"

  # Report production builds into Slack using custom plugin.
  [[context.production.plugins]]
    package = "./netlify/plugins/slack-reporting"

# Force all access through our managed TLD.
# When Netlify becomes the production site hosting for www. the subdomain will
# need changing to `www` and the status to `301`.
[[redirects]]
from = 'http://oak-web-application.netlify.app/*'
to = 'https://netlify-test.thenational.academy/:splat'
status = 302
force = true

# Force all access through our managed TLD.
# When Netlify becomes the production site hosting for www. the subdomain will
# need changing to `www` and the status to `301`.
[[redirects]]
from = 'https://oak-web-application.netlify.app/*'
to = 'https://netlify-test.thenational.academy/:splat'
status = 302
force = true

# On preview and branch deploys, use the subdomain redirect edge function
# to force all access through our managed TLD.
[[context.deploy-preview.edge_functions]]
  path = '/*'
  function = 'subdomain-redirect'
[[context.branch-deploy.edge_functions]]
  path = '/*'
  function = 'subdomain-redirect'