export { default as Heading, getNextHeadingTag } from "./Heading";
export type { HeadingTag } from "./Heading";
export { default } from "./Typography";
export { default as Span } from "./Span";
export { default as P } from "./P";
export { default as Hr } from "./Hr";
export { default as OL } from "./OL";
export { default as LI } from "./LI";
export { default as UL } from "./UL";
export { default as UnderlinedHeading } from "./UnderlinedHeading";
