export { default as Heading, getNextHeadingTag } from "./Heading.deprecated";
export type { HeadingTag } from "./Heading.deprecated";
export { default } from "./Typography.deprecated";
export { default as Span } from "./Span.deprecated";
export { default as P } from "./P.deprecated";
export { default as Hr } from "./Hr";
export { default as OL } from "./OL.deprecated";
export { default as LI } from "./LI.deprecated";
export { default as UL } from "./UL.deprecated";
export { default as UnderlinedHeading } from "./UnderlinedHeading";
