query eyfsPage($subjectSlug: String!) {
  lessons: published_mv_synthetic_unitvariant_lessons_by_keystage_18_0_0(
    where: {
      programme_fields: {
        _contains: {
          subject_slug: $subjectSlug
          keystage_slug: "early-years-foundation-stage"
        }
      }
    }
  ) {
    lesson_data
    lesson_slug
    programme_fields
    unit_slug
    unit_data
    programme_slug
    features
    order_in_unit
  }
}
