query curriculumSequence(
  $where: published_mv_curriculum_sequence_b_13_0_15_bool_exp
) {
  units: published_mv_curriculum_sequence_b_13_0_15(where: $where) {
    connection_prior_unit_description
    connection_future_unit_description
    connection_future_unit_title
    connection_prior_unit_title
    domain
    domain_id
    examboard
    examboard_slug
    keystage_slug
    lessons
    order
    planned_number_of_lessons
    phase
    phase_slug
    slug
    subject
    subject_slug
    subject_parent
    subject_parent_slug
    tags
    subjectcategories
    tier
    tier_slug
    title
    why_this_why_now
    description
    cycle
    features
    actions
    unit_options
    threads
    year
    pathway
    pathway_slug
    state
    non_curriculum
  }
}
