import curriculumUnitsEnglishSecondaryData from "./curriculumunits-english-secondary";
import subjectPhaseOptionsIncludeNewData from "./subjectPhaseOptionsIncludeNew";
import curriculumOverviewEnglishSecondaryData from "./curriculumOverview-english-secondary";

// NOTE: These are generated by `./scripts/dev/curriculum/fixtures generate` we just add in types here.
export const curriculumUnitsEnglishSecondary =
  curriculumUnitsEnglishSecondaryData;
export const subjectPhaseOptionsIncludeNew = subjectPhaseOptionsIncludeNewData;
export const curriculumOverviewEnglishSecondary =
  curriculumOverviewEnglishSecondaryData;
