/**
 * NOTE: This is automatically generated by the following script
 *
 *   ./scripts/dev/curriculum/fixtures generate
 */
export default {
  options: [
    {
      title: "Physical education",
      slug: "physical-education",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "core",
          title: "Core",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "gcse",
          title: "GCSE",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
      cycle: "2",
    },
    {
      title: "Maths",
      slug: "maths",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: null,
      cycle: "2",
    },
    {
      title: "Computing",
      slug: "computing",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "core",
          title: "Core",
        },
        {
          slug: "gcse",
          title: "GCSE",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
      cycle: "2",
    },
    {
      title: "English",
      slug: "english",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
      ],
      cycle: "2",
    },
    {
      title: "Geography",
      slug: "geography",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
      ],
      ks4_options: null,
      cycle: "1",
    },
    {
      title: "English",
      slug: "english",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
      ],
      cycle: "1",
    },
    {
      title: "Geography",
      slug: "geography",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcelb",
          title: "Edexcel B",
        },
      ],
      cycle: "2",
    },
    {
      title: "Science",
      slug: "science",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
      cycle: "1",
    },
    {
      title: "Spanish",
      slug: "spanish",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
      cycle: "2",
    },
    {
      title: "Music",
      slug: "music",
      phases: [
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
      cycle: "1",
    },
    {
      title: "Science",
      slug: "science",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
      cycle: "2",
    },
    {
      title: "German",
      slug: "german",
      phases: [
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
      cycle: "2",
    },
    {
      title: "Maths",
      slug: "maths",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: null,
      cycle: "1",
    },
    {
      title: "Citizenship",
      slug: "citizenship",
      phases: [
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "core",
          title: "Core",
        },
        {
          slug: "gcse",
          title: "GCSE",
        },
      ],
      cycle: "2",
    },
    {
      title: "Cooking and nutrition",
      slug: "cooking-nutrition",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
      ],
      ks4_options: null,
      cycle: "2",
    },
    {
      title: "Music",
      slug: "music",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
      cycle: "2",
    },
    {
      title: "Art and design",
      slug: "art",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: null,
      cycle: "2",
    },
    {
      title: "French",
      slug: "french",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
      cycle: "2",
    },
    {
      title: "History",
      slug: "history",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
      cycle: "2",
    },
    {
      title: "History",
      slug: "history",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
      cycle: "1",
    },
    {
      title: "Religious education",
      slug: "religious-education",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: [
        {
          slug: "gcse",
          title: "GCSE",
        },
      ],
      cycle: "2",
    },
    {
      title: "Design and technology",
      slug: "design-technology",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: null,
      cycle: "2",
    },
    {
      title: "RSHE (PSHE)",
      slug: "rshe-pshe",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      keystages: [
        {
          slug: "ks1",
          title: "Key Stage 1",
        },
        {
          slug: "ks2",
          title: "Key Stage 2",
        },
        {
          slug: "ks3",
          title: "Key Stage 3",
        },
        {
          slug: "ks4",
          title: "Key Stage 4",
        },
      ],
      ks4_options: null,
      cycle: "2",
    },
  ],
};
