/**
 * NOTE: This is automatically generated by the following script
 *
 *   ./scripts/dev/curriculum/fixtures generate
 */
export default {
  options: [
    {
      title: "Art and design",
      slug: "art",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Citizenship",
      slug: "citizenship",
      state: "new",
      phases: [
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Design and technology",
      slug: "design-technology",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "English",
      slug: "english",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
      ],
    },
    {
      title: "English",
      slug: "english",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
      ],
    },
    {
      title: "History",
      slug: "history",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "History",
      slug: "history",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "Maths",
      slug: "maths",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Maths",
      slug: "maths",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Music",
      slug: "music",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
    {
      title: "Religious education",
      slug: "religious-education",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Science",
      slug: "science",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
    {
      title: "Science",
      slug: "science",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
    {
      title: "QA testing only",
      slug: "testing-not-for-publication",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "RSHE (PSHE)",
      slug: "rshe-pshe",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Geography",
      slug: "geography",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcelb",
          title: "Edexcel B",
        },
      ],
    },
    {
      title: "French",
      slug: "french",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "German",
      slug: "german",
      state: "new",
      phases: [
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "Spanish",
      slug: "spanish",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "Computing",
      slug: "computing",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
    {
      title: "Cooking and nutrition",
      slug: "cooking-nutrition",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Computing",
      slug: "computing",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
    {
      title: "Cooking and nutrition",
      slug: "cooking-nutrition",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Design and technology",
      slug: "design-technology",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "French",
      slug: "french",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "Geography",
      slug: "geography",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcelb",
          title: "Edexcel B",
        },
      ],
    },
    {
      title: "Art and design",
      slug: "art",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Music",
      slug: "music",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "eduqas",
          title: "Eduqas",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
    {
      title: "RSHE (PSHE)",
      slug: "rshe-pshe",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Religious education",
      slug: "religious-education",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Spanish",
      slug: "spanish",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "German",
      slug: "german",
      state: "published",
      phases: [
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
      ],
    },
    {
      title: "Citizenship",
      slug: "citizenship",
      state: "published",
      phases: [
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: null,
    },
    {
      title: "Physical education",
      slug: "physical-education",
      state: "new",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
    {
      title: "Physical education",
      slug: "physical-education",
      state: "published",
      phases: [
        {
          slug: "primary",
          title: "Primary",
        },
        {
          slug: "secondary",
          title: "Secondary",
        },
      ],
      examboards: [
        {
          slug: "aqa",
          title: "AQA",
        },
        {
          slug: "edexcel",
          title: "Edexcel",
        },
        {
          slug: "ocr",
          title: "OCR",
        },
      ],
    },
  ],
};
