query curriculumOverview($phaseSlug: String, $subjectSlug: String) {
  curriculumOverview: published_mv_curriculum_overview_0_8 (
    where: {
      phase_slug: { _eq: $phaseSlug }
      subject_slug: { _eq: $subjectSlug }
      non_curriculum: {_eq: false}
    }
    limit: 1
  ) {
    curriculaDesc: curriculum_intent
    subjectTitle: subject
    phaseTitle: phase
    examboardTitle: examboard
    non_curriculum
  }
}
