query curriculumOverview(
  $where: published_mv_curriculum_overview_0_9_bool_exp
) {
  curriculumOverview: published_mv_curriculum_overview_0_9(
    where: $where
    limit: 1
    order_by: { non_curriculum: desc }
  ) {
    curriculaDesc: curriculum_intent
    subjectTitle: subject
    phaseTitle: phase
    examboardTitle: examboard
    nonCurriculum: non_curriculum
  }
}
