query pupilLessonListing($programmeSlug: String!, $unitSlug: String!) {
  browseData: published_mv_synthetic_unitvariant_lessons_by_year_6_0_0(
    where: {
      programme_slug: { _eq: $programmeSlug }
      unit_slug: { _eq: $unitSlug }
    }
  ) {
    lesson_title: lesson_data(path: "title")
    lesson_slug: lesson_data(path: "slug")
    order: supplementary_data(path: "order_in_unit")
    subject_title: programme_fields(path: "subject")
    subject_slug: programme_fields(path: "subject_slug")
    year_description: programme_fields(path: "year_description")
    unit_slug
    unit_title: unit_data(path: "title")
    programme_slug
    is_legacy
  }
}
