query pupilLessonListing($programmeSlug: String!, $unitSlug: String!) {
  browseData: published_mv_synthetic_unitvariant_lessons_by_year_6_0_0(
    where: {
      programme_slug: { _eq: $programmeSlug }
      unit_slug: { _eq: $unitSlug }
    }
  ) {
    lesson_data
    lesson_slug
    supplementary_data
    programme_fields
    unit_slug
    unit_data
    programme_slug
    is_legacy
  }
}
