query lessonOverview(
  $programmeSlug: String!
  $lessonSlug: String!
  $unitSlug: String!
) {
  lesson: published_mv_lesson_overview_10(
    where: {
      lessonSlug: { _eq: $lessonSlug }
      programmeSlug: { _eq: $programmeSlug }
      unitSlug: { _eq: $unitSlug }
    }
  ) {
    lessonSlug
    lessonTitle
    programmeSlug
    unitSlug
    unitTitle
    keyStageSlug
    keyStageTitle
    subjectSlug
    subjectTitle
    examBoardTitle
    tierTitle
    misconceptionsAndCommonMistakes
    lessonEquipmentAndResources
    teacherTips
    keyLearningPoints
    pupilLessonOutcome
    lessonKeywords
    copyrightContent
    contentGuidance
    additionalMaterialUrl
    supervisionLevel
    worksheetUrl
    presentationUrl
    videoMuxPlaybackId
    videoWithSignLanguageMuxPlaybackId
    transcriptSentences
    starterQuiz
    exitQuiz
    yearTitle
    hasDownloadableResources
  }
}
