mutation upsertUser($user: users_insert_input!) {
  insert_users_one(
    object: $user
    on_conflict: { constraint: users_firebaseUid_key, update_columns: [] }
  ) {
    email
    firebaseUid
    id
  }
}
