query pupilSubjectListing($yearSlug: String!) {
  data: published_mv_synthetic_programmes_by_year_14_0_0(
    where: { year_slug: { _eq: $yearSlug } }
  ) {
    programme_slug
    base_slug
    year_slug
    programme_fields
    is_legacy
    features
  }
}
