query topNav @cached(ttl: 600) {
  programmes: published_mv_synthetic_unitvariants_with_lesson_ids_by_keystage_18_0_0(
    distinct_on: programme_slug
  ) {
    programme_fields
    programme_slug
    features
    actions
  }
  phaseOptions: published_mv_curriculum_phase_options_0_4(
    where: { non_curriculum: { _eq: false } }
  ) {
    title
    slug
    phases
    keystages
    ks4_options
  }
}
