query specialistSubjectListing {
  therapyProgrammes: published_mv_specialist_1_0_3(
    distinct_on: synthetic_programme_slug
    where: {
      combined_programme_fields: { _contains: { subject_parent: "Therapies" } }
    }
  ) {
    combined_programme_fields
  }
  specialistProgrammes: published_mv_specialist_1_0_3(
    distinct_on: synthetic_programme_slug
    where: {
      combined_programme_fields: { _contains: { subject_parent: "Specialist" } }
    }
  ) {
    combined_programme_fields
  }
}
