query lessonDownloads(
  $lessonSlug: String!
  $programmeSlug: String!
  $unitSlug: String!
) {
  downloads: published_mv_downloads_7(
    where: {
      lessonSlug: { _eq: $lessonSlug }
      programmeSlug: { _eq: $programmeSlug }
      unitSlug: { _eq: $unitSlug }
    }
  ) {
    downloads
    programmeSlug
    keyStageSlug
    keyStageTitle
    lessonSlug
    lessonTitle
    subjectSlug
    subjectTitle
    unitSlug
    unitTitle
  }
}
