query curriculumPhaseOptions {
  options: published_mv_curriculum_phase_options_0_3 (where: {non_curriculum: {_eq: false}})  {
    title
    slug
    phases
    keystages
    ks4_options
    non_curriculum
  }
}
