query pupilUnitListing($baseSlug: String!) {
  browseData: published_mv_synthetic_unitvariants_with_lesson_ids_by_year_19_0_0(
    where: { base_slug: { _eq: $baseSlug } }
  ) {
    base_slug
    programme_slug
    unit_slug
    is_legacy
    programme_fields
    unit_data
    supplementary_data
    lesson_count
    lesson_expired_count
    lesson_sensitive_count
    age_restricted_lesson_count
    complex_copyright_lesson_count
    expired
    features
    actions
  }
}
