query programmeListing(
  $keyStageSlug: String
  $subjectSlug: String
  $isLegacy: Boolean
) {
  programmes: published_mv_synthetic_unitvariant_lessons_by_keystage_16_0_0(
    where: {
      _and: [
        { programme_fields: { _contains: { keystage_slug: $keyStageSlug } } }
        { programme_fields: { _contains: { subject_slug: $subjectSlug } } }
        { is_legacy: { _eq: $isLegacy } }
      ]
    }
    distinct_on: programme_slug
  ) {
    lesson_slug
    unit_slug
    unit_data
    null_unitvariant_id
    lesson_data
    programme_fields
    is_legacy
    programme_slug
    actions
  }
}
