query lessonDownloadsCanonical($lessonSlug: String!) {
  lessonDownloadsCanonical: published_mv_downloads_3_0_4(
    where: { lessonSlug: { _eq: $lessonSlug } }
  ) {
    downloads
    programmeSlug
    keyStageSlug
    keyStageTitle
    lessonSlug
    lessonTitle
    subjectSlug
    subjectTitle
    unitSlug
    unitTitle
    lessonCohort
    hasDownloadableResources
  }
}
