import {
  LessonSection,
  LessonReviewSection,
} from "@/components/PupilComponents/lessonSections";

export type LessonShareVariant = {
  sections: LessonSection[];
  reviewSections: LessonReviewSection[];
  hideYearGroup?: boolean;
};

export const PUPIL_LESSON_SHARE_VARIANTS_BASE: Record<
  string,
  LessonShareVariant
> = {
  "starter-quiz-only": {
    sections: ["overview", "intro", "starter-quiz"],
    reviewSections: ["intro", "starter-quiz"],
  },
  "exit-quiz-only": {
    sections: ["overview", "intro", "exit-quiz"],
    reviewSections: ["intro", "exit-quiz"],
  },
  "video-only": {
    sections: ["overview", "intro", "video"],
    reviewSections: ["intro", "video"],
  },
  "starter-quiz-video": {
    sections: ["overview", "intro", "starter-quiz", "video"],
    reviewSections: ["intro", "starter-quiz", "video"],
  },
  "quizzes-only": {
    sections: ["overview", "intro", "starter-quiz", "exit-quiz"],
    reviewSections: ["intro", "starter-quiz", "exit-quiz"],
  },
  "video-exit-quiz": {
    sections: ["overview", "intro", "video", "exit-quiz"],
    reviewSections: ["intro", "video", "exit-quiz"],
  },
};

/**
 * Used for when we have additional variations that are not section related
 * For example: A full lesson where hide year group is true
 */
const FULL_VARIANT: Record<"full", LessonShareVariant> = {
  full: {
    sections: ["overview", "intro", "starter-quiz", "video", "exit-quiz"],
    reviewSections: ["intro", "starter-quiz", "video", "exit-quiz"],
  },
};

export type LessonShareVariantSlug = keyof typeof PUPIL_LESSON_SHARE_VARIANTS;

/**
 * Helper function to generate new versions of PUPIL_LESSON_SHARE_VARIANTS_BASE objects with a new slug extension
 * and additional properties.
 * For example, we need a version of all the variants but with the year group hidden. So we can generate a new object
 * with the same slugs plus a new suffix but with the hideYearGroup property set to true.
 *
 * It also adds the FULL_VARIANT option so there will be a full-slugExtension version shareable
 * @param slugExtension - A hyphenated string that will be appended to the slug of each variant
 * @param fieldsToApply - An object containing the properties that should be applied to each variant
 */
const applyToAllVariantsFactory = (
  slugExtension: `-${string}`,
  fieldsToApply: Partial<LessonShareVariant>,
): typeof PUPIL_LESSON_SHARE_VARIANTS_BASE => {
  return Object.fromEntries(
    Object.entries({
      ...PUPIL_LESSON_SHARE_VARIANTS_BASE,
      ...FULL_VARIANT,
    }).map(([slug, variant]) => [
      slug + slugExtension,
      { ...variant, ...fieldsToApply },
    ]),
  );
};

/**
 * Returns all pupil lesson share variants that should be used in the app. It includes base variants plus optional
 * additional variants generated by applyToAllVariantsFactory.
 */
export const PUPIL_LESSON_SHARE_VARIANTS: typeof PUPIL_LESSON_SHARE_VARIANTS_BASE =
  (() => {
    return {
      ...PUPIL_LESSON_SHARE_VARIANTS_BASE,
      ...applyToAllVariantsFactory("-no-year", { hideYearGroup: true }),
    };
  })();

/**
 * Returns a lesson share variant if the slug has a matching variant, otherwise returns null
 * @param lessonShareSlug - the url slug for a share variant
 */
export const getLessonShareVariant = (
  lessonShareSlug: string,
): LessonShareVariant | null =>
  PUPIL_LESSON_SHARE_VARIANTS[lessonShareSlug] ?? null;

/**
 * Checks to see if variant exists with specified parameters (e.g sections and year group) and returns the matching slug
 * or null if none is found.
 * Overview and Intro are excluded from the check as they are not independently selectable when sharing a lesson
 * @param sections - the sections that should be included in the variant
 * @param hideYearGroup - whether the variant should hide the year group
 */
export const getLessonShareVariantSlug = (
  sections: LessonSection[],
  hideYearGroup: boolean = false,
): LessonShareVariantSlug | null => {
  const filterOutOverviewIntro = (s: LessonSection): boolean =>
    s !== "overview" && s !== "intro";
  const sectionsExclOverviewIntro = sections.filter(filterOutOverviewIntro);

  const match = Object.entries(PUPIL_LESSON_SHARE_VARIANTS).find(
    ([, variant]) => {
      const filteredSections = new Set(
        variant.sections.filter(filterOutOverviewIntro),
      );
      const hasAllSections: boolean = sectionsExclOverviewIntro.every(
        (section) => filteredSections.has(section),
      );
      if (!hasAllSections) return null;
      if (filteredSections.size !== sectionsExclOverviewIntro.length) {
        return null;
      }
      const hasHideYearGroup =
        Boolean(variant.hideYearGroup) === Boolean(hideYearGroup);
      if (!hasHideYearGroup) return null;
      return variant;
    },
  );
  return match?.[0] ?? null;
};
