query developmentStageUnitCount($syntheticProgrammeSlug: String!) {
  developmentStageUnitCount: published_mv_specialist_1_0_3_aggregate(
    where: {
      synthetic_programme_slug: { _eq: $syntheticProgrammeSlug }
      expired: { _is_null: true }
    }
  ) {
    aggregate {
      count(distinct: true, columns: unit_slug)
    }
  }
  developmentStageLessonCount: published_mv_specialist_1_0_3_aggregate(
    where: {
      synthetic_programme_slug: { _eq: $syntheticProgrammeSlug }
      expired: { _is_null: true }
    }
  ) {
    aggregate {
      count(distinct: true, columns: lesson_slug)
    }
  }
}
