query developmentStages($_contains: jsonb) {
  developmentStages: published_mv_specialist_1_0_1(
    where: { combined_programme_fields: { _contains: $_contains } }
  ) {
    combined_programme_fields
    synthetic_programme_slug
  }
}
