query lessonListing($programmeSlug: String!, $unitSlug: String!) {
  lessons: published_mv_synthetic_unitvariant_lessons_by_keystage_13_1_0(
    where: {
      unit_slug: { _eq: $unitSlug }
      programme_slug: { _eq: $programmeSlug }
    }
  ) {
    lesson_data
    lesson_slug
    programme_fields
    programme_slug_by_year
    null_unitvariant_id
    unit_slug
    unitvariant_id
    unit_data
    programme_slug
    is_legacy
    actions
    features
    order_in_unit
  }
}
