query lessonListing($programmeSlug: String!, $unitSlug: String!) {
  unit: published_mv_lesson_listing_5(
    where: {
      programmeSlug: { _eq: $programmeSlug }
      unitSlug: { _eq: $unitSlug }
    }
  ) {
    programmeSlug
    unitSlug
    unitTitle
    keyStageSlug
    keyStageTitle
    subjectSlug
    subjectTitle
    lessons
  }
}
