query pupilLessonOverview(
  $programmeSlug: String!
  $lessonSlug: String!
  $unitSlug: String!
) {
  lesson: published_mv_lesson_overview_3_0_0(
    where: {
      lessonSlug: { _eq: $lessonSlug }
      programmeSlug: { _eq: $programmeSlug }
      unitSlug: { _eq: $unitSlug }
    }
  ) {
    starterQuiz
    exitQuiz
  }
}
