query tierCounts($_contains: jsonb) {
  lessonCount: published_mv_synthetic_unitvariant_lessons_by_keystage_6_0_0_aggregate(
    where: { programme_fields: { _contains: $_contains } }
  ) {
    aggregate {
      count(distinct: true, columns: lesson_slug)
    }
    nodes {
      programme_fields(path: "tier_slug")
    }
  }
  unitCount: published_mv_synthetic_unitvariant_lessons_by_keystage_6_0_0_aggregate(
    where: { programme_fields: { _contains: $_contains } }
  ) {
    aggregate {
      count(distinct: true, columns: unit_slug)
    }
    nodes {
      programme_fields(path: "tier_slug")
    }
  }
}
