query unitListing($programmeSlug: String!, $isLegacy: Boolean!) {
  programme: published_mv_unit_listing_page_3_1_0(
    where: {
      programmeSlug: { _eq: $programmeSlug }
      isLegacy: { _eq: $isLegacy }
    }
  ) {
    programmeSlug
    keyStageSlug
    keyStageTitle
    subjectSlug
    subjectTitle
    tierSlug
    totalUnitCount: unitCount
    tiers
    units
    examBoardTitle
    examBoardSlug
    learningThemes
  }
}
