query curriculumUnitsIncludeNew($where: published_mv_curriculum_sequence_b_13_0_0_bool_exp) {
  units: published_mv_curriculum_sequence_b_13_0_0(where: $where) {
    connection_prior_unit_description
    connection_future_unit_description
    connection_future_unit_title
    connection_prior_unit_title
    why_this_why_now
    cycle
    features
    description
    domain
    domain_id
    examboard
    examboard_slug
    keystage_slug
    lessons
    order
    planned_number_of_lessons
    phase
    phase_slug
    slug
    state
    subject
    subject_slug
    subject_parent
    subject_parent_slug
    pathway
    pathway_slug
    tags
    subjectcategories
    tier
    tier_slug
    title
    unit_options
    threads
    year
  }
}
