query betaLessonMediaClips($lessonSlug: String!) {
  browseData: published_mv_synthetic_unitvariant_lessons_by_keystage_new_14_0_0(
    where: { lesson_slug: { _eq: $lessonSlug } }
  ) {
    lesson_slug
    unit_slug
    programme_slug
    is_legacy
    lesson_data
    unit_data
    programme_fields
    actions
    features
    order_in_unit
    media_clips
  }
}
