query specialistLessonShare(
  $programmeSlug: String
  $unitSlug: String
  $lessonSlug: String
) {
  specialistLessonShare: published_mv_specialist_1_0_4(
    where: {
      unit_slug: { _eq: $unitSlug }
      synthetic_programme_slug: { _eq: $programmeSlug }
      lesson_slug: { _eq: $lessonSlug }
    }
  ) {
    lesson_title
    combined_programme_fields
    unit_title
    expired
    contains_copyright_content
    exit_quiz
    starter_quiz
    pupil_lesson_outcome
    worksheet_url
    video_mux_playback_id
    presentation_url
    synthetic_programme_slug
    lesson_release_date
  }
}
