query subjectListing($keyStageSlug: String, $isLegacy: Boolean) {
  subjectLessons: published_mv_synthetic_unitvariant_lessons_by_keystage_6_0_0(
    where: {
      _and: [
        { programme_fields: { _contains: { keystage_slug: $keyStageSlug } } }
        { is_legacy: { _eq: $isLegacy } }
      ]
    }
  ) {
    programme_fields
    is_legacy
    null_unitvariant
    unit_slug
    lesson_slug
    programme_slug
  }
  key_stages: pf_keystages(where: { slug: { _neq: "ks5" } }) {
    keystage
    slug
    description
    display_order
  }
}
