query subjectListing($keyStageSlug: String, $isLegacy: Boolean) {
  subjectLessons: published_mv_synthetic_unitvariant_lessons_by_keystage_13_0_0(
    where: {
      _and: [
        { programme_fields: { _contains: { keystage_slug: $keyStageSlug } } }
      ]
    }
  ) {
    programme_fields
    is_legacy
    null_unitvariant_id
    lesson_data
    unit_data
    unit_slug
    lesson_slug
    programme_slug
    features
    actions
  }
  key_stages: published_mv_key_stages_2_0_0 {
    keystage: short_code
    slug
    description: title
    display_order
  }
}
