query teachersUnitOverview($programmeSlug: String!, $unitSlug: String!) {
  lessons: published_mv_synthetic_unitvariant_lessons_by_keystage_18_0_0(
    where: {
      unit_slug: { _eq: $unitSlug }
      programme_slug: { _eq: $programmeSlug }
      is_legacy: { _eq: false }
    }
  ) {
    lesson_data
    lesson_slug
    programme_fields
    programme_slug_by_year
    null_unitvariant_id
    unit_slug
    unitvariant_id
    unit_data
    programme_slug
    actions
    features
    order_in_unit
    static_lesson_list
  }
  unitSequence: published_mv_synthetic_unitvariants_with_lesson_ids_by_keystage_18_0_0(
    where: { programme_slug: { _eq: $programmeSlug } }
  ) {
    unitSlug: unit_slug
    unitTitle: unit_data(path: "title")
    unitOrder: supplementary_data(path: "unit_order")
    yearOrder: programme_fields(path: "year_display_order")
    optionalityTitle: programme_fields(path: "optionality")
    nullUnitvariantId: null_unitvariant_id
  }
}
