query canonicalLessonRedirect($incomingPath: String!) {
  redirectData: published_mv_redirects_lessons_canonical_by_keystage_1_0_0(
    where: { incoming_path: { _eq: $incomingPath } }
  ) {
    incoming_path
    outgoing_path
    redirect_type
  }
}
