query getUserListContent($userId: String!) {
  users_content(distinct_on: content_id, where: { user_id: { _eq: $userId } }) {
    users_content_lists {
      content {
        unit_slug
        programme_slug
        browse_mv {
          lessons: supplementary_data(path: "static_lesson_list")
          year: programme_fields(path: "year_description")
          keystage: programme_fields(path: "keystage")
          subject: programme_fields(path: "subject")
          unit_title: unit_data(path: "title")
          optionality_title: programme_fields(path: "optionality")
          tier: programme_fields(path: "tier")
          examboard: programme_fields(path: "examboard")
          unit_order: supplementary_data(path: "unit_order")
          year_order: programme_fields(path: "year_display_order")
        }
      }
      created_at
    }
  }
}
