query aboutCorePage($isDraftFilter: Sanity_DocumentFilter) {
  allAboutCorePage(
    where: { _: $isDraftFilter, _id: { matches: "*aboutCorePage" } }
    sort: { _updatedAt: DESC }
    limit: 1
  ) {
    id: _id
    title
    whoWeAre {
      sectionHeading
      intro {
        ...TextAndMedia
      }
      timeline {
        from {
          ...TextBlock
        }
        to {
          ...TextBlock
        }
        beyond {
          ...TextBlock
        }
        cta {
          ...CTA
        }
      }
      principles {
        ...TextBlock
      }
    }
    leadership {
      sectionHeading
      introPortableText: introRaw
    }
    board {
      sectionHeading
      introPortableText: introRaw
      boardMembers {
        ...TeamMember
      }
      documents {
        ...Attachment
      }
      governancePortableText: governanceRaw
    }
    partners {
      sectionHeading
      introPortableText: introRaw
      techPartners {
        name
        asset {
          ...ImageAsset
        }
      }
      curriculumPartners {
        name
        asset {
          ...ImageAsset
        }
      }
    }
    workWithUs {
      sectionHeading
      introPortableText: introRaw
      cards {
        joinTheTeam {
          ...Card
        }
        advisory {
          ...Card
        }
        curriculumPartner {
          ...Card
        }
        teacherResearch {
          ...Card
        }
      }
    }
    contactSection {
      infoPortableText: infoRaw
    }
    seo {
      ...Seo
    }
  }
}
