query aboutCorePage($isDraft: Boolean = false) {
  allAboutCorePage(
    where: { _: { is_draft: $isDraft }, _id: { matches: "*aboutCorePage" } }
  ) {
    id: _id
    title
    whoWeAre {
      sectionHeading
      intro {
        ...TextAndMedia
      }
      timeline {
        from {
          ...TextBlock
        }
        to {
          ...TextBlock
        }
        beyond {
          ...TextBlock
        }
        cta {
          ...CTA
        }
      }
      principles {
        ...TextBlock
      }
    }
    leadership {
      sectionHeading
      introPortableText: introRaw
    }
    board {
      sectionHeading
      introPortableText: introRaw
      documents {
        title
        file {
          asset {
            extension
            size
            url
          }
        }
      }
      governancePortableText: governanceRaw
    }
    partners {
      sectionHeading
      introPortableText: introRaw
      techPartners {
        name
        asset {
          _id
          url
        }
      }
      curriculumPartners {
        name
        asset {
          _id
          url
        }
      }
    }
    workWithUs {
      sectionHeading
      introPortableText: introRaw
      cards {
        joinTheTeam {
          ...Card
        }
        advisory {
          ...Card
        }
        curriculumPartner {
          ...Card
        }
        teacherResearch {
          ...Card
        }
      }
    }
    contactSection {
      infoPortableText: infoRaw
    }
  }
}
