query allBlogPosts($isDraft: Boolean = false, $limit: Int = 9999) {
  allNewsPost(
    where: { _: { is_draft: $isDraft } }
    sort: [{ date: DESC }]
    limit: $limit
  ) {
    ...BlogPreviewFields
  }
}
