query allBlogPosts($isDraftFilter: Sanity_DocumentFilter, $limit: Int = 9999) {
  allNewsPost(
    where: { _: $isDraftFilter }
    sort: [{ date: DESC }, { _updatedAt: DESC }]
    limit: $limit
  ) {
    ...BlogPreviewFields
  }
}
