query allPolicyPages($isDraft: Boolean = false, $limit: Int = 9999) {
  allPolicyPage(where: { _: { is_draft: $isDraft } }, limit: $limit) {
    id: _id
    title
    slug {
      current
    }
    seo {
      ...Seo
    }
  }
}
