query allWebinars($isDraftFilter: Sanity_DocumentFilter, $limit: Int = 9999) {
  allWebinar(
    where: { _: $isDraftFilter }
    sort: [{ date: DESC }, { _updatedAt: DESC }]
    limit: $limit
  ) {
    ...WebinarPreviewFields
  }
}
