fragment BlogPreviewFields on NewsPost {
  id: _id
  title
  date
  slug {
    current
  }
  author {
    id: _id
    _key
    name
    image {
      ...Image
    }
  }
  mainImage {
    ...ImageWithAltText
  }
  category {
    title
    slug {
      current
    }
  }
  summary
}
