query blogPostBySlug($slug: String, $isDraft: Boolean = false) {
  allNewsPost(
    where: { _: { is_draft: $isDraft }, slug: { current: { eq: $slug } } }
  ) {
    id: _id
    title
    date
    author {
      id: _id
      _key
      name
      image {
        asset {
          url
        }
      }
    }
    slug {
      current
    }
    mainImage {
      asset {
        _id
        url
      }
    }
    category {
      title
      slug {
        current
      }
    }
    # See resolveReferences and blogPortableTextReferences.gql
    # to see how the content is transformed to add
    # referenced entities
    summary
    contentPortableText: contentRaw
  }
}
