query blogPortableTextReferences($ids: [ID!]) {
  allDocument(where: { _id: { in: $ids } }) {
    _id
    _type
    ... on Webinar {
      slug {
        current
      }
    }
    ... on SanityImageAsset {
      _id
      url
    }
    ... on Video {
      ...Video
    }
  }
}
