query caseStudyLibraryPage(
  $slug: String
  $isDraftFilter: Sanity_DocumentFilter
  $limit: Int
) {
  allCaseStudy(
    where: { _: $isDraftFilter, slug: { current: { neq: $slug } } }
query caseStudyLibraryPage($isDraftFilter: Sanity_DocumentFilter, $limit: Int) {
  allCaseStudy (
    where: {
      _: $isDraftFilter
    }
    limit: $limit
  ) {
    title
    slug {
      current
    }
    tag
    summaryRaw
    video {
      ...Video
    }
    textRaw
    image {
      ...ImageWithAltText
    }
    publishedAt
    content {
      heading
      label
      anchorSlug {
        current
      }
      contentRaw
    }
    showGetInTouchPanel
    getInTouchPanel {
      personName
      personImage {
        ...ImageWithAltText
      }
      jobRole
      institutionName
    }
  }
}
