query curriculumCorePage($isDraftFilter: Sanity_DocumentFilter) {
  allCurriculumCorePage(
    where: { _: $isDraftFilter, _id: { matches: "*curriculumCorePage" } }
    sort: { _updatedAt: DESC }
    limit: 1
  ) {
    id: _id
    title
    heading
    summaryPortableText: summaryRaw
    summaryCardImage {
      ...Image
    }
    info {
      ...TextBlock
    }
    gettingStarted {
      ...TextBlock
    }
    ourApproach {
      ...TextBlock
    }
    elements {
      title
      posts {
        title
        post {
          ...BlogPreviewFields
        }
      }
    }
    seo {
      ...Seo
    }

    #   relatedBlogs {
    #     author {
    #       isCurrent
    #     }
    #     category {
    #       title
    #     }
    #     contentRaw
    #   }
    #   relatedWebinars {
    #     date
    #     _id
    #   }
  }
}
