query curriculumOverview(
  $isDraftFilter: Sanity_DocumentFilter
  $subjectTitle: String
  $phaseSlug: String
) {
  allCurriculumInfoPageOverview(
    where: {
      _: $isDraftFilter
      subject: { eq: $subjectTitle }
      phase: { matches: $phaseSlug }
    }
    sort: { _updatedAt: DESC }
    limit: 1
  ) {
    id: _id
    curriculumExplainer {
      explainerRaw
    }
    subjectPrinciples
    partnerBio
    curriculumPartner {
      name
      image {
        ...Image
      }
    }
    curriculumPartnerOverviews {
      curriculumPartner {
        name
        image {
          ...Image
        }
      }
      partnerBio
      partnerBioPortableTextRaw
    }
    video {
      ...Video
    }
    videoAuthor
    videoExplainer
    curriculumSeoTextRaw
  }
}
