query curriculumCorePage($isDraft: Boolean = false) {
  allCurriculumCorePage(
    where: {
      _: { is_draft: $isDraft }
      _id: { matches: "*curriculumCorePage" }
    }
  ) {
    id: _id
    title
    heading
    summaryPortableText: summaryRaw
    info {
      ...TextBlock
    }
    gettingStarted {
      ...TextBlock
    }
    ourApproach {
      ...TextBlock
    }
    elements {
      title
      posts {
        title
        post {
          title
          slug {
            current
          }
        }
      }
    }
    seo {
      ...Seo
    }

    #   relatedBlogs {
    #     author {
    #       isCurrent
    #     }
    #     category {
    #       title
    #     }
    #     contentRaw
    #   }
    #   relatedWebinars {
    #     date
    #     _id
    #   }
  }
}
