query getInvolvedPage($isDraftFilter: Sanity_DocumentFilter) {
  allNewAboutCorePageGetInvolved(
    where: {
      _: $isDraftFilter
      _id: { matches: "*newAboutCorePage.getInvolved" }
    }
    sort: { _updatedAt: DESC }
    limit: 1
  ) {
    id: _id
    header {
      introText
    }
    collaborate {
      researchPanelTextRaw
      feedbackTextRaw
    }
    workWithUs {
      textRaw
      image {
        ...ImageWithAltText
      }
    }
    seo {
      ...Seo
    }
  }
}
