query landingPageBySlug($slug: String, $isDraftFilter: Sanity_DocumentFilter) {
  allLandingPage(
    where: { _: $isDraftFilter, slug: { current: { eq: $slug } } }
    sort: { _updatedAt: DESC }
    limit: 1
  ) {
    ...LandingPage
  }
}
