query oaksImpactCaseStudyListPage($isDraftFilter: Sanity_DocumentFilter) {
  allCaseStudy (
    where: {
      _: $isDraftFilter
    }
  ) {
    slug {
      current
    },
    video {
      ...Video
    },
    image {
      ...ImageWithAltText
    }
    publishedAt,
    textRaw,
  }
}