query oaksImpactPage($isDraftFilter: Sanity_DocumentFilter) {
  caseStudy: allNewAboutCorePageOaksImpact(
    where: {
      _: $isDraftFilter
      _id: { matches: "*newAboutCorePage.oaksImpact" }
    }
    sort: { _updatedAt: DESC }
    limit: 1
  ) {
    id: _id
    header {
      introText
      video {
        ...Video
      }
      videoDescription
    }
    statsSection {
      textBlock {
        ...TextBlock
      }
      stats {
        icon {
          ...ImageWithAltTextAndDarkMode
        }
        heading
        textRaw
      }
    }
    schoolQuotes {
      heading
      cards {
        logo {
          ...ImageWithAltText
        }
        summary
        quote {
          text
          role
          organisation
          attribution
        }
        headshot {
          ...ImageWithAltText
        }
      }
    }
  }
  otherCaseStudies: allCaseStudy(
    where: { _: $isDraftFilter }
    sort: { publishedAt: DESC }
    limit: 3
  ) {
    video {
      ...Video
    }
    slug {
      current
    }
    image {
      ...ImageWithAltText
    }
    title
    tag
  }
}
