query planningCorePage($isDraftFilter: Sanity_DocumentFilter) {
  allPlanningCorePage(
    sort: { _updatedAt: DESC }
    limit: 1
    where: { _: $isDraftFilter, _id: { matches: "*planningCorePage" } }
  ) {
    id: _id
    title
    heading
    summaryPortableText: summaryRaw
    summaryCardImage {
      ...Image
    }
    lessonElements {
      _type
      introQuiz {
        ...Card
      }
      video {
        ...Card
      }
      slides {
        ...Card
      }
      worksheet {
        ...Card
      }
      exitQuiz {
        ...Card
      }
    }
    lessonElementsCTA {
      ...CTA
    }
    stepsHeading
    steps {
      step1 {
        ...Card
      }
      step2 {
        ...Card
      }
      step3 {
        ...Card
      }
      step4 {
        ...Card
      }
    }
    stepsCTA {
      ...CTA
    }
    learnMoreHeading
    learnMoreBlock1 {
      ...TextAndMedia
    }
    learnMoreBlock2 {
      ...TextAndMedia
    }
    seo {
      ...Seo
    }
  }
}
