query portableTextReferences($ids: [ID!]) {
  allDocument(where: { _id: { in: $ids } }) {
    id: _id
    _type
    ...InternalLinkFields
    ... on SanityImageAsset {
      _id
      url
    }
    ... on Video {
      ...Video
    }
  }
}
