fragment WebinarPreviewFields on Webinar {
  id: _id
  title
  slug {
    current
  }
  date
  video {
    ...Video
  }
  hosts {
    id: _id
    _key
    name
    image {
      ...Image
    }
  }
  category {
    title
    slug {
      current
    }
  }
  summaryPortableText: summaryRaw
}
