query webinarBySlug($slug: String, $isDraftFilter: Sanity_DocumentFilter) {
  allWebinar(
    where: { _: $isDraftFilter, slug: { current: { eq: $slug } } }
    sort: { _updatedAt: DESC }
    limit: 1
  ) {
    id: _id
    title
    slug {
      current
    }
    date
    summaryPortableText: summaryRaw
    category {
      title
      slug {
        current
      }
    }
    hosts {
      id: _id
      _key
      name
      image {
        ...Image
      }
    }
    video {
      ...Video
    }
    seo {
      ...Seo
    }
  }
}
