query webinarBySlug($slug: String, $isDraft: Boolean = false) {
  allWebinar(
    where: { _: { is_draft: $isDraft }, slug: { current: { eq: $slug } } }
  ) {
    id: _id
    title
    slug {
      current
    }
    date
    summaryPortableText: summaryRaw
    hosts {
      id: _id
      _key
      name
      image {
        asset {
          url
        }
      }
    }
  }
}
