fragment WebinarPreviewFields on Webinar {
  id: _id
  title
  slug {
    current
  }
  date
  video {
    ...Video
  }
  category {
    title
    slug {
      current
    }
  }
  summaryPortableText: summaryRaw
}
