query specialistLessonDownloads(
  $programmeSlug: String
  $unitSlug: String
  $lessonSlug: String
) {
  specialistLessonDownloads: published_mv_specialist_1_0_3(
    where: {
      unit_slug: { _eq: $unitSlug }
      synthetic_programme_slug: { _eq: $programmeSlug }
      lesson_slug: { _eq: $lessonSlug }
    }
  ) {
    lesson_title
    combined_programme_fields
    unit_title
    expired
    contains_copyright_content
    exit_quiz
    starter_quiz
    pupil_lesson_outcome
    worksheet_asset_object
    worksheet_url
    video_mux_playback_id
    video_title
    exit_quiz_asset_object
    presentation_url
    slidedeck_asset_object
    starter_quiz_asset_object
  }
  restrictions: published_mv_lesson_content_published_5_0_0(
    where: { lesson_slug: { _eq: $lessonSlug } }
  ) {
    geo_restricted
    login_required
  }
}
