query pupilProgrammeListing($baseSlug: String!) {
  data: published_mv_synthetic_programmes_by_year_18_0_0(
    where: { base_slug: { _eq: $baseSlug } }
  ) {
    programme_slug
    year_slug
    programme_fields
    actions
    features
  }
}
