# Re-usable workflow for examining contents of the triggering GitHub event.
# Use like
# ```
# jobs:
#  dump_github_event:
#    uses: ./.github/workflows/reusable_dump_event.yml
# ```

on:
  workflow_call:

jobs:
  run:
    name: dump GitHub event
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo GITHUB_ACTION: $GITHUB_ACTION
          echo GITHUB_WORKFLOW: $GITHUB_WORKFLOW
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
