query eyfsVideos($lessonIds: [String!]) {
  published_mv_lesson_content_published_9_0_0(
    where: { lesson_slug: { _in: $lessonIds } }
  ) {
    video_mux_playback_id
    video_id
    video_title
  }
}
