query pupilLesson(
  $where: published_mv_synthetic_unitvariant_lessons_by_year_6_0_0_bool_exp
) {
  browseData: published_mv_synthetic_unitvariant_lessons_by_year_6_0_0(
    where: $where
  ) {
    lesson_slug
    unit_slug
    programme_slug
    is_legacy
    lesson_data
    unit_data
    programme_fields
    supplementary_data
  }
}
