query pupilLesson(
  $lessonSlug: String!
  $unitSlug: String
  $programmeSlug: String
  $isLegacy: Boolean
) {
  browseData: published_mv_synthetic_unitvariant_lessons_by_year_6_0_0(
    where: {
      _and: [
        { lesson_slug: { _eq: $lessonSlug } }
        {
          _or: [
            { unit_slug: { _eq: $unitSlug } }
            {
              unit_slug: { _is_null: true }
              _not: { unit_slug: { _is_null: false } }
            }
          ]
        }
        {
          _or: [
            { programme_slug: { _eq: $programmeSlug } }
            {
              programme_slug: { _is_null: true }
              _not: { programme_slug: { _is_null: false } }
            }
          ]
        }
        {
          _or: [
            { is_legacy: { _eq: $isLegacy } }
            {
              is_legacy: { _is_null: true }
              _not: { is_legacy: { _is_null: false } }
            }
          ]
        }
      ]
    }
  ) {
    lesson_slug
    unit_slug
    programme_slug
    is_legacy
    lesson_data
    unit_data
    programme_fields
    supplementary_data
  }
}
